import fs from 'fs';
import path from 'path';

// --- Base Authentic Products Definition ---

const MACHINES = [
  {
    name: 'Sage Bambino Plus',
    brand: 'Sage',
    category: 'maquinas',
    subCategory: 'Semiautomáticas',
    price: 449,
    oldPrice: 499,
    score: 8.4,
    stars: 4.5,
    badge: 'Mejor para empezar',
    shortDesc: 'Compacta, calentamiento ThermoJet en 3 segundos y vaporizador automático asistido con sensor de temperatura.',
    image: '/assets/products/sage-bambino.png',
    specs: { 'Caldera / Calentamiento': 'ThermoJet (3 segundos)', 'Portafiltro': '54 mm acero inoxidable', 'Presión': '15 bar (OPV a 9 bar)', 'Vaporizador': 'Automático con 3 temperaturas y texturas', 'Capacidad Agua': '1.9 L', 'Dimensiones': '19.5 x 32 x 31 cm', 'Peso': '4.95 kg' },
    pros: ['Calentamiento instantáneo en 3s', 'Vaporización automática de calidad microespuma', 'Tamaño ultra-compacto'],
    cons: ['Portafiltro de 54mm en vez de 58mm', 'Bandeja de goteo pequeña'],
    subscores: { espresso: 8.3, vapor: 8.5, facilidad: 9.4, construccion: 8.2, precio: 8.8 },
  },
  {
    name: 'Sage Bambino',
    brand: 'Sage',
    category: 'maquinas',
    subCategory: 'Manuales',
    price: 349,
    oldPrice: 399,
    score: 8.2,
    stars: 4.3,
    badge: 'Mejor compacta',
    shortDesc: 'La versión pura de la Bambino con vaporizador manual tradicional y extracción con preinfusión a baja presión.',
    image: '/assets/products/sage-bambino.png',
    specs: { 'Caldera / Calentamiento': 'ThermoJet (3s)', 'Portafiltro': '54 mm', 'Presión': '15 bar regulada', 'Vaporizador': 'Manual profesional', 'Capacidad Agua': '1.4 L', 'Dimensiones': '16 x 31 x 30 cm', 'Peso': '4.5 kg' },
    pros: ['Excelente relación calidad/precio', 'Calentamiento instantáneo', 'Vaporizador manual con buena potencia'],
    cons: ['Sin sensor de temperatura automático', 'Carcasa ligera'],
    subscores: { espresso: 8.1, vapor: 8.0, facilidad: 8.9, construccion: 8.0, precio: 9.1 },
  },
  {
    name: 'Sage Barista Express',
    brand: 'Sage',
    category: 'maquinas',
    subCategory: 'Con molinillo',
    price: 629,
    oldPrice: 699,
    score: 8.6,
    stars: 4.6,
    badge: 'Todo en uno',
    shortDesc: 'La cafetera todo en uno más vendida del mundo: molinillo cónico de precisión integrado con control digital PID y manómetro.',
    image: '/assets/products/sage-barista-express.png',
    specs: { 'Molinillo': 'Muelas cónicas acero inox (18 ajustes)', 'Calentamiento': 'Thermocoil 1600W con PID', 'Portafiltro': '54 mm acero inox', 'Manómetro': 'Analógico de presión de extracción', 'Capacidad Grano': '250 g', 'Capacidad Agua': '2.0 L', 'Peso': '10.6 kg' },
    pros: ['Setup completo en un solo aparato', 'Control de temperatura PID preciso', 'Manómetro de extracción en tiempo real'],
    cons: ['El molinillo integrado tiene saltos entre puntos', 'Requiere limpieza frecuente del molino'],
    subscores: { espresso: 8.5, vapor: 8.3, facilidad: 8.8, construccion: 8.7, precio: 8.9 },
  },
  {
    name: 'Sage Barista Touch',
    brand: 'Sage',
    category: 'maquinas',
    subCategory: 'Con molinillo',
    price: 999,
    oldPrice: 1199,
    score: 8.8,
    stars: 4.7,
    badge: 'Pantalla táctil',
    shortDesc: 'Pantalla táctil interactiva a color con recetas preconfiguradas y personalizables, sistema ThermoJet y espumado automático.',
    image: '/assets/products/sage-barista-touch.png',
    specs: { 'Pantalla': 'Táctil a color interactiva', 'Molinillo': 'Muelas cónicas integradas', 'Calentamiento': 'ThermoJet 3 segundos', 'Vapor': 'Automático Auto MilQ', 'Capacidad Agua': '2.0 L', 'Peso': '10.3 kg' },
    pros: ['Interfaz intuitiva con guardado de perfiles', 'Calentamiento en 3 segundos', 'Texturizado de leche automático'],
    cons: ['Precio más elevado', 'Ajuste de molido por pasos'],
    subscores: { espresso: 8.7, vapor: 8.8, facilidad: 9.6, construccion: 8.6, precio: 8.3 },
  },
  {
    name: 'Sage Dual Boiler',
    brand: 'Sage',
    category: 'maquinas',
    subCategory: 'Doble caldera',
    price: 1299,
    oldPrice: 1499,
    score: 9.3,
    stars: 4.8,
    badge: 'Doble caldera',
    shortDesc: 'Doble caldera de acero inoxidable con doble control PID digital, grupo comercial de 58 mm saturado y válvula OPV regulable.',
    image: '/assets/products/sage-dual-boiler.png',
    specs: { 'Calderas': 'Doble caldera inox (Café 0.3L + Vapor 0.95L)', 'Grupo': '58 mm comercial con resistencia activa', 'Control': 'Doble PID digital regulable grado a grado', 'Válvula': 'OPV a 9 bar regulable', 'Capacidad Agua': '2.5 L', 'Peso': '13.6 kg' },
    pros: ['Estabilidad térmica insuperable a este precio', 'Extracción y vapor simultáneos', 'Portafiltro estándar de 58mm'],
    cons: ['Estética de electrodoméstico', 'Mantenimiento de juntas periódicas'],
    subscores: { espresso: 9.6, vapor: 9.3, facilidad: 8.7, construccion: 8.9, precio: 9.4 },
  },
  {
    name: 'Lelit Anna PL41TEM',
    brand: 'Lelit',
    category: 'maquinas',
    subCategory: 'Semiautomáticas',
    price: 549,
    oldPrice: 599,
    score: 8.7,
    stars: 4.6,
    badge: 'Mejor control PID',
    shortDesc: 'Fabricada en Italia con caldera de latón de 250 ml, control digital PID de temperatura y manómetro analógico retroiluminado.',
    image: '/assets/products/lelit-anna.png',
    specs: { 'Caldera': 'Latón 250 ml', 'Grupo': '57 mm Lelit', 'Control': 'PID digital integrado', 'Manómetro': 'Sí, presión bomba', 'Cuerpo': 'Acero inoxidable pulido', 'Depósito': '2.7 L', 'Peso': '7.2 kg' },
    pros: ['Control PID preciso', 'Caldera de latón con gran inercia térmica', 'Construcción robusta en acero'],
    cons: ['Medida de portafiltro de 57mm (menos accesorios estándar)', 'Tiempo de calentamiento ~10 min'],
    subscores: { espresso: 8.8, vapor: 8.2, facilidad: 8.4, construccion: 9.0, precio: 9.2 },
  },
  {
    name: 'Lelit Glenda PL41PLUS',
    brand: 'Lelit',
    category: 'maquinas',
    subCategory: 'Semiautomáticas',
    price: 699,
    oldPrice: 749,
    score: 8.8,
    stars: 4.7,
    badge: 'Grupo 58mm',
    shortDesc: 'Grupo profesional estándar de 58 mm comercial con caldera de latón de 300 ml y control digital de temperatura PID.',
    image: '/assets/products/lelit-glenda-pl41plus.png',
    specs: { 'Caldera': 'Latón 300 ml', 'Grupo': '58 mm estándar comercial', 'Control': 'PID electrónico', 'Válvula': 'Solenoide 3 vías', 'Depósito': '2.7 L', 'Peso': '9.0 kg' },
    pros: ['Grupo estándar comercial de 58mm', 'Mayor caldera para estabilidad', 'PID integrado'],
    cons: ['Monocaldera (espera entre café y vapor)', 'Diseño sobrio'],
    subscores: { espresso: 9.0, vapor: 8.4, facilidad: 8.5, construccion: 9.1, precio: 9.0 },
  },
  {
    name: 'Lelit Victoria PL91T',
    brand: 'Lelit',
    category: 'maquinas',
    subCategory: 'Semiautomáticas',
    price: 899,
    oldPrice: 999,
    score: 9.1,
    stars: 4.8,
    badge: 'Centro de control LCC',
    shortDesc: 'Línea VIP con display gráfico LCC OLED: preinfusión programable, shot timer, caldera de latón de 300 ml y portafiltro de 58 mm.',
    image: '/assets/products/lelit-victoria-pl91t.png',
    specs: { 'Caldera': 'Latón 300 ml', 'Grupo': '58 mm VIP', 'Display': 'LCC gráfico multifunción', 'Preinfusión': 'Programable digitalmente', 'Shot Timer': 'Integrado en pantalla', 'Peso': '9.2 kg' },
    pros: ['Centro de control LCC muy completo', 'Preinfusión configurable', 'Shot timer automático al extraer'],
    cons: ['Monocaldera', 'Bandeja de goteo superficial'],
    subscores: { espresso: 9.3, vapor: 8.6, facilidad: 9.1, construccion: 9.2, precio: 9.1 },
  },
  {
    name: 'Lelit Mara X V2',
    brand: 'Lelit',
    category: 'maquinas',
    subCategory: 'Intercambiador (HX)',
    price: 1199,
    oldPrice: 1299,
    score: 9.4,
    stars: 4.9,
    badge: 'Reina del HX',
    shortDesc: 'La máquina HX más silenciosa y estable del mercado con legendario grupo E61, doble sonda de temperatura y selector de perfil.',
    image: '/assets/products/lelit-mara-x.png',
    specs: { 'Sistema': 'Intercambiador de calor (HX) con control de temperatura de café prioritario', 'Grupo': 'E61 termosifónico', 'Bomba': 'Vibratoria ultra-silenciosa con soporte patentado', 'Caldera': 'Acero inox 1.8 L', 'Dimensiones': '22 x 41 x 35 cm', 'Peso': '18.8 kg' },
    pros: ['No requiere purgas de enfriamiento (cooling flush)', 'Extracción y vapor potente simultáneo', 'Bomba casi inaudible'],
    cons: ['Requiere 20-25 min de calentamiento del grupo E61', 'Peso elevado'],
    subscores: { espresso: 9.5, vapor: 9.5, facilidad: 8.8, construccion: 9.6, precio: 9.5 },
  },
  {
    name: 'Lelit Bianca V3',
    brand: 'Lelit',
    category: 'maquinas',
    subCategory: 'Doble caldera',
    price: 2199,
    oldPrice: 2399,
    score: 9.7,
    stars: 5.0,
    badge: 'Referencia Prosumer',
    shortDesc: 'Doble caldera independiente de acero inox, bomba rotativa silenciosa y paleta (paddle) de madera para perfilado de flujo manual.',
    image: '/assets/products/lelit-bianca-v3.png',
    specs: { 'Calderas': 'Doble caldera inox (Café 0.8L + Vapor 1.5L)', 'Grupo': 'E61 modificado con válvula de flujo', 'Perfilado': 'Paddle mecánico manual 0-12 bar', 'Bomba': 'Rotativa comercial (conexión a red o depósito)', 'Depósito': 'Reposicionable en 3 lados', 'Peso': '26.5 kg' },
    pros: ['Control total de caudal y presión en tiempo real', 'Bomba rotativa silenciosa con conexión directa a red', 'Detalles en madera noble de nogal'],
    cons: ['Tamaño y peso considerable', 'Curva de aprendizaje para dominar el perfilado'],
    subscores: { espresso: 9.8, vapor: 9.8, facilidad: 8.6, construccion: 9.7, precio: 9.6 },
  },
  {
    name: 'Gaggia Classic Pro',
    brand: 'Gaggia',
    category: 'maquinas',
    subCategory: 'Semiautomáticas',
    price: 429,
    oldPrice: 479,
    score: 8.5,
    stars: 4.5,
    badge: 'Clásico italiano',
    shortDesc: 'El icono del espresso casero desde 1991: grupo comercial de 58 mm, electroválvula de 3 vías y vaporizador profesional.',
    image: '/assets/products/gaggia-classic-pro.png',
    specs: { 'Caldera': 'Aluminio tradicional 100 ml', 'Grupo': '58 mm comercial latón cromado', 'Electroválvula': '3 vías para pastilla seca', 'Vapor': 'Lanza profesional de dos orificios', 'Carcasa': 'Acero inoxidable cepillado', 'Peso': '7.3 kg' },
    pros: ['Enorme comunidad y facilidad de modificación (Gaggiuino / PID)', 'Chasis indestructible', 'Grupo de 58mm comercial'],
    cons: ['Sin PID de fábrica (termostato bimétalico)', 'Capacidad de caldera pequeña'],
    subscores: { espresso: 8.0, vapor: 8.3, facilidad: 8.2, construccion: 9.0, precio: 9.0 },
  },
  {
    name: 'Rancilio Silvia',
    brand: 'Rancilio',
    category: 'maquinas',
    subCategory: 'Semiautomáticas',
    price: 599,
    oldPrice: 649,
    score: 8.6,
    stars: 4.6,
    badge: 'Robusta de latón',
    shortDesc: 'Diseño industrial indestructible con caldera de latón marino de 300 ml, grupo comercial de 58 mm y marco de acero.',
    image: '/assets/products/rancilio-silvia.png',
    specs: { 'Caldera': 'Latón marino 300 ml aislada', 'Grupo': '58 mm latón forjado', 'Vapor': 'Lanza comercial multidireccional', 'Chasis': 'Hierro y acero inoxidable', 'Depósito': '2.0 L', 'Peso': '14.0 kg' },
    pros: ['Construcción de nivel comercial para durar décadas', 'Potencia de vapor referente en monocaldera', 'Grupo 58mm estándar'],
    cons: ['Requiere técnica de temp-surfing sin PID', 'Tiempo de calentamiento ~15 min'],
    subscores: { espresso: 8.4, vapor: 9.1, facilidad: 7.9, construccion: 9.7, precio: 8.8 },
  },
  {
    name: 'Rancilio Silvia Pro X',
    brand: 'Rancilio',
    category: 'maquinas',
    subCategory: 'Doble caldera',
    price: 1549,
    oldPrice: 1699,
    score: 9.5,
    stars: 4.9,
    badge: 'Doble caldera con PID',
    shortDesc: 'Doble caldera independiente de latón con doble control PID digital, preinfusión suave programable (Soft Infusion) y manómetro.',
    image: '/assets/products/rancilio-silvia-pro-x.png',
    specs: { 'Calderas': 'Doble caldera (Café latón 0.3L + Vapor inox 1.0L)', 'Control': 'Doble PID digital regulable', 'Preinfusión': 'Soft Infusion a baja presión', 'Grupo': '58 mm profesional', 'Manómetro': 'Analógico frontal', 'Peso': '20.0 kg' },
    pros: ['Estabilidad térmica de precisión quirúrgica', 'Preinfusión suave que previene la canalización', 'Potencia de vapor continua'],
    cons: ['Estética industrial austera', 'Sin opción de conexión directa a red'],
    subscores: { espresso: 9.7, vapor: 9.6, facilidad: 8.9, construccion: 9.6, precio: 9.4 },
  },
  {
    name: 'Profitec GO',
    brand: 'Profitec',
    category: 'maquinas',
    subCategory: 'Semiautomáticas',
    price: 899,
    oldPrice: 949,
    score: 9.2,
    stars: 4.8,
    badge: 'Diseño alemán',
    shortDesc: 'Ingeniería alemana compacta con caldera de latón de 400 ml, calentamiento rápido Fast Heat-Up, pantalla OLED PID y manómetro.',
    image: '/assets/products/profitec-go.png',
    specs: { 'Caldera': 'Latón 0.4 L', 'Grupo': '58 mm comercial con campana de latón', 'Control': 'PID frontal con shot timer', 'Calentamiento': 'Fast Heat-Up (~5-7 min)', 'OPV': 'Regulable externamente', 'Peso': '12.9 kg' },
    pros: ['Calentamiento rápido en menos de 7 minutos', 'Válvula OPV regulable desde el exterior', 'Pantalla OLED con temporizador integrado'],
    cons: ['Monocaldera (espera para vapor)', 'Bandeja de goteo algo justa'],
    subscores: { espresso: 9.4, vapor: 8.8, facilidad: 9.2, construccion: 9.6, precio: 9.3 },
  },
  {
    name: 'Profitec Drive',
    brand: 'Profitec',
    category: 'maquinas',
    subCategory: 'Doble caldera',
    price: 2699,
    oldPrice: 2899,
    score: 9.8,
    stars: 5.0,
    badge: 'Tope de gama',
    shortDesc: 'El buque insignia con doble caldera de acero inox, grupo E61 con perfilado de flujo activo, bomba rotativa y encendido programable.',
    image: '/assets/products/profitec-drive.png',
    specs: { 'Calderas': 'Doble caldera inox (Café 0.75L + Vapor 2.0L)', 'Grupo': 'E61 con Flow Control integrado', 'Bomba': 'Rotativa comercial ultra-silenciosa', 'Display': 'OLED discreto con múltiples menús', 'Auto-On': 'Programador semanal de encendido', 'Peso': '31.0 kg' },
    pros: ['Construcción suprema de precisión alemana', 'Caldera de vapor descomunal de 2.0L', 'Perfilado de flujo y preinfusión activa'],
    cons: ['Inversión de alto presupuesto', 'Peso de 31 kg'],
    subscores: { espresso: 9.9, vapor: 9.9, facilidad: 8.8, construccion: 9.9, precio: 9.3 },
  },
  {
    name: 'Rocket Appartamento',
    brand: 'Rocket Espresso',
    category: 'maquinas',
    subCategory: 'Intercambiador (HX)',
    price: 1399,
    oldPrice: 1499,
    score: 9.2,
    stars: 4.8,
    badge: 'Estética icónica',
    shortDesc: 'Diseño icónico de Milán con paneles circulares troquelados, legendario grupo E61 y caldera de cobre de 1.8 L con intercambiador.',
    image: '/assets/products/rocket-appartamento.png',
    specs: { 'Caldera': 'Cobre 1.8 L con intercambiador termosifónico', 'Grupo': 'E61 macizo de latón', 'Presostato': 'Sirai / Mater de alta durabilidad', 'Lanzas': 'Anti-quemaduras (Cool Touch)', 'Dimensiones': '27.4 x 42.5 x 36 cm', 'Peso': '20.0 kg' },
    pros: ['Estética que enamora en cualquier cocina', 'Potencia de vapor impecable', 'Chasis y grupo E61 de máxima robustez'],
    cons: ['Sin control PID digital de fábrica', 'Requiere purga de enfriamiento ocasional'],
    subscores: { espresso: 8.9, vapor: 9.6, facilidad: 8.4, construccion: 9.7, precio: 8.9 },
  },
  {
    name: 'Flair 58 Plus',
    brand: 'Flair Espresso',
    category: 'maquinas',
    subCategory: 'Manuales',
    price: 649,
    oldPrice: 699,
    score: 9.6,
    stars: 5.0,
    badge: 'Palanca manual',
    shortDesc: 'Extracción manual pura de palanca con portafiltro estándar de 58 mm comercial, precalentamiento eléctrico activo y manómetro.',
    image: '/assets/products/flair-58-plus.png',
    specs: { 'Cámara': 'Acero inox con calentador eléctrico integrado (3 niveles)', 'Portafiltro': '58 mm comercial con mango de nogal', 'Presión': 'Manual directa hasta 12 bar', 'Manómetro': 'Analógico en vástago de émbolo', 'Peso': '5.5 kg' },
    pros: ['Perfilado de presión manual absoluto', 'Precalentamiento eléctrico que elimina la pérdida térmica', 'Portafiltro de 58mm compatible con cestas de competición'],
    cons: ['No tiene vaporizador de leche', 'Totalmente manual shot a shot'],
    subscores: { espresso: 9.6, vapor: 6.0, facilidad: 8.2, construccion: 9.6, precio: 9.6 },
  },
  {
    name: 'La Pavoni Europiccola',
    brand: 'La Pavoni',
    category: 'maquinas',
    subCategory: 'Manuales',
    price: 749,
    oldPrice: 829,
    score: 8.9,
    stars: 4.6,
    badge: 'Patrimonio histórico',
    shortDesc: 'Pieza de museo del diseño industrial italiano desde 1961: caldera de latón macizo y palanca mecánica de pistón directo.',
    image: '/assets/products/la-pavoni-europiccola.png',
    specs: { 'Caldera': 'Latón cromado 0.8 L (8 tazas)', 'Grupo': 'Palanca mecánica de latón 51 mm', 'Vapor': 'Lanza de vapor continua desde caldera', 'Base': 'Acero cromado', 'Peso': '5.5 kg' },
    pros: ['Diseño eterno y reparabilidad de por vida', 'Extracción manual auténtica con gran crema', 'Vapor potente e instantáneo'],
    cons: ['Curva de aprendizaje empinada', 'Se sobrecalienta tras varios cafés consecutivos'],
    subscores: { espresso: 8.0, vapor: 8.9, facilidad: 7.5, construccion: 9.8, precio: 8.9 },
  },
  {
    name: 'Technivorm Moccamaster KBG Select',
    brand: 'Moccamaster',
    category: 'maquinas',
    subCategory: 'Filtro / Goteo',
    price: 249,
    oldPrice: 289,
    score: 9.4,
    stars: 4.9,
    badge: 'Referencia en Filtro',
    shortDesc: 'Fabricada a mano en Holanda con certificación ECBC y SCA: elemento calefactor de cobre que mantiene los 92-96 °C exactos.',
    image: '/assets/products/moccamaster-kbg-select.png',
    specs: { 'Capacidad': '1.25 L (10 tazas)', 'Elemento': 'Cobre puro de doble resistencia', 'Temperatura': '92 °C - 96 °C constante', 'Selector': 'Jarra completa o media jarra con flujo adaptado', 'Placa': 'Térmica con auto-apagado tras 40 min', 'Peso': '2.8 kg' },
    pros: ['La mejor cafetera de filtro por goteo del mundo', 'Temperatura y tiempo de contacto de agua certificados SCA', 'Garantía de 5 años del fabricante'],
    cons: ['Solo para café de filtro (no espresso)', 'Jarra de cristal requiere cuidado'],
    subscores: { espresso: 9.9, vapor: 5.0, facilidad: 9.8, construccion: 9.8, precio: 9.5 },
  },
];

const GRINDERS = [
  {
    name: 'Fellow Ode Gen 2',
    brand: 'Fellow',
    category: 'molinos',
    subCategory: 'Eléctricos',
    price: 399,
    oldPrice: 449,
    score: 9.4,
    stars: 4.9,
    badge: 'Rey del Filtro',
    shortDesc: 'Muelas planas Gen 2 de 64 mm de acero inoxidable optimizadas para café de filtro, tecnología antiestática ionizada y parada automática.',
    image: '/assets/products/fellow-ode-gen-2.png',
    specs: { 'Muelas': 'Planas 64 mm acero inoxidable Gen 2', 'Ajuste': '31 pasos micrométricos', 'Retención': 'Tecnología ionizadora antiestática (retención <0.1g)', 'Motor': 'Accionamiento directo con PID y parada auto', 'Capacidad': '100 g', 'Peso': '4.5 kg' },
    pros: ['Claridad y separación de sabores suprema en filtro', 'Cero estática gracias a los iones', 'Parada automática al terminar'],
    cons: ['Diseñado exclusivamente para filtro (no muele para espresso)', 'Tolva de tamaño single dose'],
    subscores: { espresso: 9.2, vapor: 5.0, facilidad: 9.6, construccion: 9.5, precio: 9.3 },
  },
  {
    name: 'Fellow Opus Conical Burr',
    brand: 'Fellow',
    category: 'molinos',
    subCategory: 'Eléctricos',
    price: 199,
    oldPrice: 229,
    score: 8.8,
    stars: 4.6,
    badge: 'Todo terreno',
    shortDesc: 'Muelas cónicas C-Mill de 40 mm y 6 aspas para moler desde espresso fino hasta Cold Brew grueso con ajuste micrométrico interno.',
    image: '/assets/products/fellow-opus.png',
    specs: { 'Muelas': 'Cónicas 40 mm acero al carbono', 'Ajuste': '41 pasos exteriores + micro-ajuste interno (+/- 0.33 pasos)', 'Rango': 'Espresso, Moka, Filtro, Prensa francesa, Cold Brew', 'Tecnología': 'Antiestática integrada', 'Peso': '2.3 kg' },
    pros: ['Capacidad real de moler para espresso y filtro', 'Tecnología antiestática limpia', 'Diseño Fellow moderno y compacto'],
    cons: ['Ajuste fino interno requiere consultar la guía', 'Carcasa exterior plástica'],
    subscores: { espresso: 8.5, vapor: 5.0, facilidad: 8.7, construccion: 8.6, precio: 9.2 },
  },
  {
    name: 'Niche Zero Grinder',
    brand: 'Niche',
    category: 'molinos',
    subCategory: 'Eléctricos Single Dose',
    price: 599,
    oldPrice: 649,
    score: 9.6,
    stars: 5.0,
    badge: 'Cero Retención',
    shortDesc: 'El molinillo single dose que revolucionó el espresso casero: muelas cónicas comerciales Mazzer de 63 mm y flujo directo sin retención.',
    image: '/assets/products/niche-zero.png',
    specs: { 'Muelas': 'Cónicas Mazzer 63 mm acero endurecido', 'Ajuste': 'Continuo sin pasos (stepless) con esfera grabada', 'Retención': 'Menor a 0.1 g garantizada', 'Motor': 'Baja velocidad 330 RPM silencioso', 'Peso': '4.1 kg' },
    pros: ['Retención cero sin necesidad de fuelles', 'Muelas Mazzer 63mm con cuerpo y dulzura excepcionales', 'Motor ultra silencioso'],
    cons: ['Importación y disponibilidad limitada', 'Enfocado 90% a espresso'],
    subscores: { espresso: 9.4, vapor: 5.0, facilidad: 9.8, construccion: 9.7, precio: 9.4 },
  },
  {
    name: 'KINGrinder K6',
    brand: 'KINGrinder',
    category: 'molinos',
    subCategory: 'Manuales',
    price: 119,
    oldPrice: 139,
    score: 9.3,
    stars: 4.8,
    badge: 'Mejor Calidad / Precio',
    shortDesc: 'Molinillo manual con muelas heptagonales de 48 mm y anillo exterior de micro-ajuste de 16 micras por clic.',
    image: '/assets/products/kingrinder-k6.png',
    specs: { 'Muelas': 'Heptagonales 48 mm acero inox', 'Ajuste': 'Exterior con 60 clics por vuelta (16 µm por clic)', 'Compatibilidad': 'Espresso y Filtro', 'Capacidad': '35 g', 'Cuerpo': 'Aluminio anodizado', 'Peso': '630 g' },
    pros: ['Ajuste exterior comodísimo sin abrir el depósito', 'Velocidad de molienda rápida para espresso', 'Calidad de molienda al nivel de molinos de 400€'],
    cons: ['Molienda manual (1 minuto para espresso fino)', 'Grip requiere fuerza para tuestes claros'],
    subscores: { espresso: 9.0, vapor: 5.0, facilidad: 8.9, construccion: 9.3, precio: 9.8 },
  },
];

const ACCESSORIES = [
  {
    name: 'Fellow Stagg EKG Hervidor Cuello de Cisne',
    brand: 'Fellow',
    category: 'accesorios',
    subCategory: 'Hervidores',
    price: 169,
    oldPrice: 189,
    score: 9.6,
    stars: 4.9,
    badge: 'Favorito de Baristas',
    shortDesc: 'Control de temperatura grado a grado (40-100 °C), pantalla LCD oculta, cronómetro de vertido y pico de cuello de cisne de flujo laminar.',
    image: '/assets/products/fellow-stagg.png',
    specs: { 'Capacidad': '0.9 L', 'Potencia': '1200 W calentamiento rápido', 'Control': 'Rango 40 °C a 100 °C grado a grado', 'Hold': 'Mantiene la temperatura 60 minutos', 'Material': 'Acero inoxidable 304', 'Peso': '1.2 kg' },
    pros: ['Control de flujo de agua milimétrico', 'Mantiene la temperatura 60 minutos', 'Cronómetro integrado para infusiones'],
    cons: ['Precio premium para un hervidor', 'Capacidad máxima de 0.9L'],
    subscores: { espresso: 9.9, vapor: 5.0, facilidad: 9.8, construccion: 9.7, precio: 9.0 },
  },
  {
    name: 'AeroPress Original Coffee Maker',
    brand: 'AeroPress',
    category: 'accesorios',
    subCategory: 'Cafeteras Manuales',
    price: 38,
    oldPrice: 42,
    score: 9.5,
    stars: 4.9,
    badge: 'Indestructible',
    shortDesc: 'El método de inmersión y presión más versátil, limpio y rápido: prepara cafés sedosos y sin acidez amarga en menos de 2 minutos.',
    image: '/assets/products/aeropress-original.png',
    specs: { 'Material': 'Polipropileno libre de BPA y ftalatos', 'Capacidad': '250 ml', 'Tiempo de infusión': '1-2 minutos', 'Filtro': 'Microfiltros de papel o metal', 'Peso': '230 g' },
    pros: ['Prácticamente indestructible y perfecta para viajes', 'Limpieza instantánea en 5 segundos', 'Versatilidad infinita de recetas'],
    cons: ['Prepara una taza individual a la vez', 'Estética plástica funcional'],
    subscores: { espresso: 8.8, vapor: 5.0, facilidad: 9.9, construccion: 9.8, precio: 9.9 },
  },
  {
    name: 'Chemex Cafetera Clásica 6 Tazas',
    brand: 'Chemex',
    category: 'accesorios',
    subCategory: 'Cafeteras Manuales',
    price: 48,
    oldPrice: 55,
    score: 9.3,
    stars: 4.8,
    badge: 'Icono del Diseño',
    shortDesc: 'Exhibida en el MoMA de Nueva York: vidrio de borosilicato resistente al calor con collar de madera pulida y lazo de cuero.',
    image: '/assets/products/chemex-classic.png',
    specs: { 'Capacidad': '900 ml (6 tazas)', 'Material': 'Vidrio de borosilicato no poroso', 'Collar': 'Madera de abedul natural con cordón de cuero', 'Filtros': 'Papel Chemex de triple pliegue', 'Peso': '580 g' },
    pros: ['Taza limpia y brillante sin sedimentos ni aceites pesados', 'Diseño eterno de colección', 'Capacidad para servir a varias personas'],
    cons: ['Vidrio frágil que requiere lavado manual cuidadoso', 'Filtros especiales propietarios'],
    subscores: { espresso: 8.5, vapor: 5.0, facilidad: 9.0, construccion: 9.4, precio: 9.2 },
  },
  {
    name: 'Bialetti Moka Express 3 Tazas',
    brand: 'Bialetti',
    category: 'accesorios',
    subCategory: 'Cafeteras Tradicionales',
    price: 26,
    oldPrice: 32,
    score: 8.7,
    stars: 4.6,
    badge: 'Patrimonio Clásico',
    shortDesc: 'La cafetera italiana original de ocho lados patentada por Alfonso Bialetti en 1933, fabricada en aluminio pulido con válvula de seguridad.',
    image: '/assets/products/bialetti-moka.png',
    specs: { 'Capacidad': '130 ml (3 tazas espresso)', 'Material': 'Aluminio fundido', 'Válvula': 'Inspeccionable de seguridad Bialetti', 'Mango': 'Termoplástico ergonómico', 'Peso': '400 g' },
    pros: ['Cuerpo denso y clásico espresso de toda la vida', 'Inmortal y económica', 'Fácil de usar sobre cualquier fuego'],
    cons: ['No apta para inducción directa (aluminio)', 'Requiere controlar el fuego para no quemar el café'],
    subscores: { espresso: 8.0, vapor: 5.0, facilidad: 8.6, construccion: 9.2, precio: 9.7 },
  },
];

const COFFEES = [
  {
    name: 'Nomad Coffee — Samuel Washed Espresso',
    brand: 'Nomad Coffee',
    category: 'cafe',
    subCategory: 'Espresso',
    price: 18.5,
    oldPrice: null,
    score: 9.4,
    stars: 4.9,
    badge: 'Tostador Referente BCN',
    shortDesc: 'Proceso lavado de alta montaña en Huila, Colombia. Notas de flor de azahar, panela melosa y lima dulce con cuerpo sedoso.',
    image: '/assets/products/nomad-samuel.png',
    specs: { 'Origen': 'Huila, Colombia', 'Productor': 'Samuel Riascos', 'Variedad': 'Caturra / Colombia', 'Proceso': 'Lavado fermentación 36h', 'Altitud': '1.750 msnm', 'Tueste': 'Espresso ligero/medio', 'Peso': '250 g' },
    pros: ['Tueste fresco semanal bajo demanda', 'Trazabilidad directa con el caficultor', 'Equilibrio perfecto entre acidez cítrica y dulzor'],
    cons: ['Precio de especialidad', 'Disponibilidad estacional limitada'],
    subscores: { espresso: 9.4, vapor: 5.0, facilidad: 9.5, construccion: 9.5, precio: 9.2 },
  },
  {
    name: 'Nomad Coffee — Shakiso Hadeso Natural',
    brand: 'Nomad Coffee',
    category: 'cafe',
    subCategory: 'Filtro y Espresso',
    price: 21.0,
    oldPrice: null,
    score: 9.5,
    stars: 5.0,
    badge: 'Microlote Etíope',
    shortDesc: 'Microlote natural de Guji, Etiopía. Explosión de notas de arándano maduro, jazmín silvestre, melocotón en almíbar y té negro bergamota.',
    image: '/assets/products/nomad-shakiso.png',
    specs: { 'Origen': 'Guji, Etiopía', 'Estación': 'Hadeso Washing Station', 'Variedad': 'Heirloom autóctonas', 'Proceso': 'Natural secado en camas africanas', 'Altitud': '2.100 msnm', 'Tueste': 'Omniroast (Filtro / Espresso moderno)', 'Peso': '250 g' },
    pros: ['Perfil floral y afrutado de campeonato', 'Claridad increíble en V60 y Chemex', 'Altitud extrema de 2100m'],
    cons: ['Perfil muy afrutado que no busca el café tradicional amargo'],
    subscores: { espresso: 9.5, vapor: 5.0, facilidad: 9.5, construccion: 9.6, precio: 9.3 },
  },
  {
    name: 'Nomad Coffee — Pink Bourbon Fermentado',
    brand: 'Nomad Coffee',
    category: 'cafe',
    subCategory: 'Microlote Exótico',
    price: 26.0,
    oldPrice: null,
    score: 9.7,
    stars: 5.0,
    badge: 'Edición Limitada',
    shortDesc: 'Varietal exótico Pink Bourbon con fermentación anaeróbica controlada. Notas de fruta de la pasión, papaya, caramelo salado y pomelo rosa.',
    image: '/assets/products/nomad-pink-bourbon.png',
    specs: { 'Origen': 'San Adolfo, Huila, Colombia', 'Productor': 'Rodrigo Sánchez', 'Variedad': 'Pink Bourbon 100%', 'Proceso': 'Anaeróbico 72h', 'Altitud': '1.800 msnm', 'Tueste': 'Filtro / Espresso de competición', 'Peso': '250 g' },
    pros: ['Uno de los varietales más codiciados del mundo', 'Complejidad aromática inolvidable', 'Puntuación SCA > 89 puntos'],
    cons: ['Precio alto por su rareza'],
    subscores: { espresso: 9.7, vapor: 5.0, facilidad: 9.4, construccion: 9.8, precio: 9.0 },
  },
  {
    name: 'Syra Coffee — Atitlán Guatemala',
    brand: 'Syra Coffee',
    category: 'cafe',
    subCategory: 'Espresso',
    price: 14.0,
    oldPrice: null,
    score: 9.1,
    stars: 4.7,
    badge: 'Mejor Diario',
    shortDesc: 'Cosechado junto al lago Atitlán en tierras volcánicas. Notas reconfortantes de chocolate negro 70%, nuez moscada y caramelo toffee.',
    image: '/assets/products/syra-atitlan.png',
    specs: { 'Origen': 'Lago Atitlán, Guatemala', 'Variedad': 'Bourbon / Catuai', 'Proceso': 'Lavado tradicional', 'Altitud': '1.600 msnm', 'Tueste': 'Espresso omniroast', 'Peso': '250 g' },
    pros: ['Excelente café de especialidad para todos los días', 'Cuerpo achocolatado ideal para cafés con leche y capuchinos', 'Precio muy accesible'],
    cons: ['Perfil clásico con menor acidez frutal'],
    subscores: { espresso: 9.0, vapor: 5.0, facilidad: 9.6, construccion: 9.2, precio: 9.6 },
  },
  {
    name: 'Syra Coffee — Bahire Specialty Coffee',
    brand: 'Syra Coffee',
    category: 'cafe',
    subCategory: 'Filtro',
    price: 16.5,
    oldPrice: null,
    score: 9.2,
    stars: 4.8,
    badge: 'Afrutado & Dulce',
    shortDesc: 'Café de pequeños productores de Sidama. Notas frescas de albaricoque, miel de azahar y hierba limón con final dulce prolongado.',
    image: '/assets/products/syra-bahire.png',
    specs: { 'Origen': 'Sidama, Etiopía', 'Variedad': 'Heirloom', 'Proceso': 'Lavado', 'Altitud': '1.950 msnm', 'Tueste': 'Filtro ligero', 'Peso': '250 g' },
    pros: ['Taza limpia y floral', 'Tueste fresco semanal en Barcelona', 'Gran relación calidad/precio en Etiopía lavado'],
    cons: ['Requiere molienda fina y agua de mineralización débil para brillar'],
    subscores: { espresso: 9.1, vapor: 5.0, facilidad: 9.4, construccion: 9.3, precio: 9.4 },
  },
  {
    name: 'Right Side Coffee — Abasambi Natural Espresso',
    brand: 'Right Side Coffee',
    category: 'cafe',
    subCategory: 'Espresso',
    price: 12.0,
    oldPrice: null,
    score: 9.3,
    stars: 4.8,
    badge: 'Tueste de Precisión',
    shortDesc: 'Procesado de forma natural con secado lento. Notas de fresa silvestre madura, licor de cereza, chocolate con leche y vainilla.',
    image: '/assets/products/rightside-abasambi.png',
    specs: { 'Origen': 'Nyamasheke, Ruanda', 'Productor': 'Cooperativa Abasambi', 'Variedad': 'Red Bourbon 100%', 'Proceso': 'Natural', 'Altitud': '1.700 msnm', 'Tueste': 'Espresso de campeonato', 'Peso': '250 g' },
    pros: ['Tostado por el campeón de tueste Joaquín Parra', 'Notas dulces muy intensas en espresso', 'Precio insuperable'],
    cons: ['Acidez natural presente en extracción'],
    subscores: { espresso: 9.3, vapor: 5.0, facilidad: 9.5, construccion: 9.5, precio: 9.7 },
  },
  {
    name: 'Right Side Coffee — Ancizar Narváez Filtro',
    brand: 'Right Side Coffee',
    category: 'cafe',
    subCategory: 'Filtro',
    price: 16.0,
    oldPrice: null,
    score: 9.4,
    stars: 4.9,
    badge: 'Finca Trazable',
    shortDesc: 'Microlote de Finca El Paraíso en Nariño. Notas elegantes de manzana roja, sirope de arce, flor blanca y té verde.',
    image: '/assets/products/rightside-ancizar.png',
    specs: { 'Origen': 'Nariño, Colombia', 'Productor': 'Ancizar Narváez', 'Variedad': 'Castillo', 'Proceso': 'Lavado 48h fermentación', 'Altitud': '1.900 msnm', 'Tueste': 'Filtro nórdico', 'Peso': '250 g' },
    pros: ['Claridad y elegancia en taza', 'Excelente desarrollo del grano sin notas amargas', 'Comercio directo transparente'],
    cons: ['Tueste muy ligero pensado para método de goteo'],
    subscores: { espresso: 9.4, vapor: 5.0, facilidad: 9.4, construccion: 9.5, precio: 9.4 },
  },
  {
    name: 'Three Marks Coffee — Seasonal Espresso',
    brand: 'Three Marks',
    category: 'cafe',
    subCategory: 'Espresso',
    price: 21.0,
    oldPrice: null,
    score: 9.3,
    stars: 4.8,
    badge: 'Poblenou Roasters',
    shortDesc: 'Pack de temporada con dos orígenes frescos seleccionados por Marc, Marco y Marco. Notas vivas de ciruela negra, avellana tostada y cacao.',
    image: '/assets/products/threemarks-espresso.png',
    specs: { 'Origen': 'Blend de temporada (Colombia + Ruanda)', 'Variedad': 'Bourbon / Caturra', 'Proceso': 'Lavado y Natural', 'Altitud': '1.800 msnm', 'Tueste': 'Espresso moderno', 'Peso': '2 x 250 g' },
    pros: ['Pack doble de 500g muy conveniente', 'Tostadores de culto en la escena de Barcelona', 'Cuerpo y crema aterciopelada'],
    cons: ['Solo se vende en formato 2x250g'],
    subscores: { espresso: 9.2, vapor: 5.0, facilidad: 9.6, construccion: 9.4, precio: 9.3 },
  },
];

const ALL_RAW = [...MACHINES, ...GRINDERS, ...ACCESSORIES, ...COFFEES];

function generateTypeScript(): string {
  let code = `import { Product } from '../core/domain/Product';
import { BuyingGuide } from '../core/domain/Roaster';
import { CoffeeScore } from '../core/domain/Score';

export interface BarcelonaRoaster {
  name: string;
  district: string;
  priceKg: number;
  origins: string;
  roastFreq: string;
  score: number;
  signature: string;
}

export const CATEGORIES = [
  { id: 'maquinas', name: 'Máquinas de Café', icon: '', count: ${MACHINES.length} },
  { id: 'molinos', name: 'Molinos de Café', icon: '', count: ${GRINDERS.length} },
  { id: 'accesorios', name: 'Accesorios Barista', icon: '', count: ${ACCESSORIES.length} },
  { id: 'cafe', name: 'Café de Especialidad', icon: '', count: ${COFFEES.length} }
];

export const BRANDS = [
  'Sage',
  'Lelit',
  "De'Longhi",
  'Gaggia',
  'Rancilio',
  'Profitec',
  'Rocket Espresso',
  'Flair Espresso',
  'La Pavoni',
  'Moccamaster',
  'Fellow',
  'Niche',
  'KINGrinder',
  'AeroPress',
  'Chemex',
  'Bialetti',
  'Nomad Coffee',
  'Syra Coffee',
  'Right Side Coffee',
  'Three Marks'
];

export const PRODUCTS: Product[] = [
`;

  for (const p of ALL_RAW) {
    const slug = p.name.toLowerCase()
      .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)+/g, '');

    const query = encodeURIComponent(`${p.brand} ${p.name.split('—')[0].trim()}`);

    const stores = [
      {
        name: 'Amazon',
        price: p.price,
        inStock: true,
        url: `https://www.amazon.es/s?k=${query}&tag=thecoffeescore-21`,
        isBest: true,
      },
      {
        name: p.category === 'cafe' ? 'Tienda Oficial Tostador' : 'Tienda Especializada Barista',
        price: Math.round(p.price * 1.04),
        inStock: true,
        url: p.category === 'cafe'
          ? (p.brand.toLowerCase().includes('nomad') ? 'https://nomadcoffee.es/collections/cafe' :
             p.brand.toLowerCase().includes('syra') ? 'https://syra.coffee/collections/all' :
             p.brand.toLowerCase().includes('right') ? 'https://rightsidecoffee.com/collections/all' :
             'https://threemarkscoffee.com/collections/all')
          : `https://www.amazon.es/s?k=${query}+barista&tag=thecoffeescore-21`,
      },
      {
        name: 'El Corte Inglés',
        price: Math.round(p.price * 1.08),
        inStock: true,
        url: `https://www.amazon.es/s?k=${query}&tag=thecoffeescore-21`,
      },
    ];

    code += `  {
    id: ${JSON.stringify(slug)},
    slug: ${JSON.stringify(slug)},
    name: ${JSON.stringify(p.name)},
    brand: ${JSON.stringify(p.brand)},
    category: ${JSON.stringify(p.category)},
    subCategory: ${JSON.stringify(p.subCategory)},
    price: ${p.price},
    oldPrice: ${p.oldPrice ? p.oldPrice : 'null'},
    historicalAveragePrice: ${Math.round(p.price * 1.05)},
    isOffer: ${p.oldPrice !== null},
    score: new CoffeeScore(${p.score}),
    stars: ${p.stars},
    badge: ${JSON.stringify(p.badge)},
    image: ${JSON.stringify(p.image)},
    gallery: [${JSON.stringify(p.image)}],
    shortDesc: ${JSON.stringify(p.shortDesc)},
    subscores: ${JSON.stringify(p.subscores)},
    pros: ${JSON.stringify(p.pros)},
    cons: ${JSON.stringify(p.cons)},
    specs: ${JSON.stringify(p.specs)},
    stores: ${JSON.stringify(stores, null, 6).replace(/\n/g, '\n    ')}
  },
`;
  }

  code += `];

export const BARCELONA_ROASTERS: BarcelonaRoaster[] = [
  {
    name: 'Nomad Coffee',
    district: 'Poblenou / Born',
    priceKg: 38,
    origins: 'Colombia, Etiopía, Ruanda, Kenia',
    roastFreq: 'Semanal (Lunes y Miércoles)',
    score: 9.4,
    signature: 'Samuel Washed / Shakiso Hadeso'
  },
  {
    name: 'Right Side Coffee',
    district: 'Castelldefels / BCN',
    priceKg: 36,
    origins: 'Colombia, Etiopía, Guatemala, Brasil',
    roastFreq: 'Semanal (Bajo demanda)',
    score: 9.3,
    signature: 'Abasambi / Ancizar Narváez'
  },
  {
    name: 'Three Marks Coffee',
    district: 'Fort Pienc / Poblenou',
    priceKg: 40,
    origins: 'Kenia, Ruanda, Colombia, Brasil',
    roastFreq: 'Semanal (Martes)',
    score: 9.3,
    signature: 'Seasonal Espresso / Rwanda Gitesi'
  },
  {
    name: 'Syra Coffee',
    district: 'Gràcia / Eixample',
    priceKg: 32,
    origins: 'Guatemala, Etiopía, Brasil, Honduras',
    roastFreq: 'Semanal continuo',
    score: 9.1,
    signature: 'Atitlán / Bahire'
  },
  {
    name: "Satan's Coffee Corner",
    district: 'Gòtic / Eixample',
    priceKg: 35,
    origins: 'Etiopía, Kenia, Colombia',
    roastFreq: 'Semanal',
    score: 9.0,
    signature: 'Right Side Custom Roast'
  },
  {
    name: 'SlowMov',
    district: 'Gràcia',
    priceKg: 39,
    origins: 'Etiopía, Burundi, Colombia',
    roastFreq: 'Semanal (Loring S15)',
    score: 9.2,
    signature: 'Microlotes trazables'
  },
  {
    name: 'Hidden Coffee Roasters',
    district: 'Les Corts / El Born',
    priceKg: 36,
    origins: 'Nicaragua, Etiopía, Brasil',
    roastFreq: 'Semanal',
    score: 9.1,
    signature: 'Volcán Azul / Finca Bethania'
  },
  {
    name: 'Morrow Coffee',
    district: 'Eixample Esquerra',
    priceKg: 34,
    origins: 'Colombia, Etiopía, Brasil',
    roastFreq: 'Semanal (En tienda)',
    score: 8.9,
    signature: 'Tueste propio en directo'
  }
];

export const BUYING_GUIDES: BuyingGuide[] = [
  {
    id: 'guia-primera-cafetera-espresso',
    slug: 'primera-cafetera-espresso-manual',
    title: 'Tu primera cafetera de espresso: qué buscar y qué ignorar',
    subtitle: 'Por qué los bares de presión no importan, cómo el control de temperatura define el sabor y qué presupuesto mínimo necesitas para no tirar el dinero.',
    category: 'Guías de compra',
    readTime: '8 min de lectura',
    image: '/assets/products/sage-bambino.png',
    featured: true,
    publishedAt: '2026-08-15'
  },
  {
    id: 'guia-molinillo-antes-que-cafetera',
    slug: 'por-que-el-molinillo-es-mas-importante-que-la-cafetera',
    title: 'Por qué el molinillo es más importante que la propia cafetera',
    subtitle: 'Un análisis con microscopio de la distribución de partículas: la diferencia entre muelas cónicas y planas en la extracción real del café.',
    category: 'Técnica y equipo',
    readTime: '12 min de lectura',
    image: '/assets/products/fellow-ode-gen-2.png',
    featured: false,
    publishedAt: '2026-08-10'
  },
  {
    id: 'guia-sage-vs-delonghi',
    slug: 'sage-bambino-plus-vs-delonghi-dedica',
    title: 'Sage Bambino Plus vs De’Longhi Dedica: la comparativa definitiva',
    subtitle: 'Enfrentamos las dos cafeteras compactas más vendidas del mercado en cinco pruebas ciegas de extracción, estabilidad térmica y vapor.',
    category: 'Cara a cara',
    readTime: '10 min de lectura',
    image: '/assets/products/sage-bambino.png',
    featured: false,
    publishedAt: '2026-08-05'
  },
  {
    id: 'guia-mejores-molinos-calidad-precio',
    slug: 'mejores-molinos-cafe-calidad-precio',
    title: 'Los mejores molinos de café de 2026 por rango de precio',
    subtitle: 'De 50€ a 600€: qué modelo comprar según si tomas espresso, filtro o ambos, medido con retención y uniformidad.',
    category: 'Rankings',
    readTime: '15 min de lectura',
    image: '/assets/products/coffee-grinders-compare.png',
    featured: false,
    publishedAt: '2026-08-01'
  },
  {
    id: 'guia-setup-barista-casa-menos-500',
    slug: 'setup-barista-en-casa-por-menos-de-500-euros',
    title: 'Cómo montar un setup de barista completo en casa por menos de 500 €',
    subtitle: 'La combinación exacta de máquina, molinillo y accesorios imprescindibles para conseguir espresso de cafetería sin arruinarte.',
    category: 'Presupuestos',
    readTime: '7 min de lectura',
    image: '/assets/products/aeropress.png',
    featured: false,
    publishedAt: '2026-07-28'
  }
];
`;

  return code;
}

const finalCode = generateTypeScript();
fs.writeFileSync(path.resolve('src/data/catalog.ts'), finalCode);
console.log('✅ Catálogo impecable generado con exactitud en src/data/catalog.ts.');
